kind: ConfigMap
apiVersion: v1
metadata:
  name: test
  namespace: {{ $.Values.operators.neuvector.namespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $.Values.sync-waves.configmap | quote }}
immutable: false
data:
  test: test