apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/syncwave: {{ $.Values.syncwaves.serviceaccount | quote }}
  name: job-wait-neuvector-operator-sa
  namespace: {{ $.Values.operators.neuvector.namespace | quote }}
