kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: job-wait-neuvector-operator-crb
  annotations:
    argocd.argoproj.io/sync-wave: {{ $.Values.sync-waves.rolebinding | quote }}
subjects:
  - kind: ServiceAccount
    name: job-wait-neuvector-operator-sa
    namespace: {{ $.Values.operators.neuvector.namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: job-wait-neuvector-operator-role
