kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: {{ $.Values.syncwaves.patch | quote }}
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  name: job-patch-operator-role
rules:
  - verbs:
      - get
      - list
      - watch
      - patch
    apiGroups:
      - operators.coreos.com
    resources:
      - installplans
