apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: {{ $.Values.syncwaves.job | quote }}
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  name: job-wait-neuvector-operator-sa
  namespace: {{ $.Values.operators.neuvector.namespace | quote }}
