apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/syncwave: {{ $.Values.syncwaves.job | quote }}
  name: wait-neuvector-crd
  namespace: {{ $.Values.operators.neuvector.namespace | quote }}
spec:
  selector: {}
  template:
    metadata:
      name: wait-neuvector-crd
    spec:
      containers:
        - name: wait-neuvector-crd
          image: registry.redhat.io/openshift4/ose-cli
          command:
            - /bin/bash
            - -c
            - |
              export HOME=/tmp/clo
              echo ""
              echo -n "Waiting for the Neuvector CRD to be available."
              until oc wait --for condition=established --timeout=60s crd/neuvectors.apm.neuvector.com -n {{ $.Values.operators.neuvector.namespace | quote }}
              do
                echo -n "---still waiting"
                sleep $SLEEP
              done
              echo -n "DONE"
          env:
          - name: SLEEP
            value: "5"
      restartPolicy: OnFailure
      serviceAccount: job-wait-neuvector-operator-sa
      serviceAccountName: job-wait-neuvector-operator-sa
      terminationGracePeriodSeconds: 30            
