kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: job-patch-operator-crb
  annotations:
    argocd.argoproj.io/sync-wave: {{ $.Values.syncwaves.patch | quote }}
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
subjects:
  - kind: ServiceAccount
    name: job-patch-operator-sa
    namespace: {{ $.Values.operators.neuvector.namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: job-patch-operator-role
