apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: neuvector-og
  namespace: {{ $.Values.operators.neuvector.namespace | quote }}
  annotations:
    argocd.argoproj.io/syncwave: {{ $.Values.syncwaves.operatorgroup | quote }}
spec:
  targetNamespaces:
  - {{ $.Values.operators.neuvector.namespace | quote }}
