apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/neuvector-certified-operator.atos-neuvector: ""
  annotations:
    argocd.argoproj.io/syncwave: {{ $.Values.syncwaves.subscription | quote }}
  name: neuvector-certified-operator
  namespace: openshift-operators
spec:
  channel: beta
  installPlanApproval: Manual
  name: neuvector-certified-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
