apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: Relevante Applikationen
  destinations:
    - name: '*'
      namespace: '*'
      server: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - description: Alle Rechte
      groups:
        - cluster-admins
      name: admin
      policies:
        - 'p, proj:applications:admin, applications, *, applications/*, allow'
  sourceRepos:
    - '*'