apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: group-ssa
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: applications
  source:
    path: group-ssa
    repoURL: 'https://github.com/saschasgit/group-ssa.git'
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - Validate=false