= Red Hat GitOps Operator
:toc:

Wenn man den Red Hat GitOps Operator nutzen möchte, um ein seitens Red Hat supportetes ArgoCD zu haben, müssen ein paar Dinge beachtet werden.

In diesem Repository befinden sich diverse Dateien, um testweise mit dem Red hat GitOps Operator etwas zu experimentieren. Einige Dateien sind nicht notwendig, sondern eher ein Resultat meines Mangels an Aufräumwillen. Aber alle relevanten Dateien sind hier in dieser Erläuterungen erwähnt und erklärt.

Eine Dokumentation des Operators findet man hier:

https://github.com/redhat-developer/gitops-operator/blob/master/docs/OpenShift%20GitOps%20Usage%20Guide.md

Zunächst ist zu beachten, dass sich die DEX-Konfiguration ab Version 1.6 ändert. Im Bereich "spec" ist dann der Abschnitt "dex" deprecated und es gibt einen neuen Abschnitt "sso", in welchem die DEX Konfiguration zu beschreiben ist. Das ist Stand heute (November 2022) deswegen wichtig, weil der Channel "stable" derzeit eine 1.5.7 ausrollt, der Channel "latest" hingegen eine 1.6.2.

== Installieren des Operators

Datei: 1_subscription_without_default_instance.yaml

Der Red Hat GitOps Operator installiert in der Standardkonfiguration nicht nur den Operator, sondern auch eine erste ArgoCD Instanz im Namespace "openshift-gitops". Das ist nett gemeint und auch nützlich, um sich die Konfiguration der Instanz anzuschauen. Jedoch möchte man diese Instanz vielleicht nicht haben, weil diese eine Konfiguration hat, die einem nicht gefällt. Diese Instanz ist jedoch gemanaged und kann nicht einfach verändert werden.

Die Lösung ist daher, den Red Hat GitOps Operator ohne diese Instanz zu erstellen. Dies geht, indem man in die Beschreibung der Subscription die Variable "DISABLE_DEFAULT_ARGOCD_INSTANCE" auf "true" setzt:

[source,yaml]
----
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/openshift-gitops-operator.openshift-operators: ""
  name: openshift-gitops-operator
  namespace: openshift-operators
spec:
  channel: latest
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  config:
    env:
    - name: DISABLE_DEFAULT_ARGOCD_INSTANCE
      value: "true"
----

Darüber hinaus wird der Operator zunächst mit minimalen Rechten bereitgestellt und kann daher nur Ressourcen in seinem eigenen Namespace verwalten. Da dies nicht sehr hilfreich ist, kann man dies über eine Umgebungsvariable so erweitern, dass er Clusterweit tätig sein kann:

[source,yaml]
----
  config:
    env:
    - name: ARGOCD_CLUSTER_CONFIG_NAMESPACES
      value: openshift-gitops
----

Beides ist hier in der erwähnten Datei so konfiguriert. Was zusätzlich beim Installieren des Operators auch ein Namespace "openshift-gitops" mit angelegt wird. In diesem wird eigentlich die Default-Instanz installiert. Das Anlegen des Namespaces wurde hier nicht deaktiviert, da dieser dann für die eigene ArgoCD Instanz genutzt wird.

== Konfiguration der Instanz

Datei: 2_argocd_instance.yaml

Zunächst muss der Name der Instanz geändert werden. Es sollte nicht der Standardname "openshift-gitops" sein. Da der Operator so konfiguriert wurde, dass keine Standardinstanz installiert wird, würde er die Instanz mit dem Namen "openshift-gitops" bei einem Update löschen.

Wenn man dann Gruppen für die Berechtigungen in ArgoCD definiert, muss man natürlich beachten, dass man auf dem Cluster Gruppen anlegt, die zu den Gruppen passen, die man in der Instanz (Ressource Kind: ArgoCD) oder in Applikationsprojekten (Ressource Kind: AppProject) definiert.

Das Thema RBAC ist ein eigenständiges, umfassendes Thema und kann nicht im Rahmen dieser Installation erklärt werden. Diese Installation hier hat folgende Konfiguration:

[source,yaml]
----
  rbac:
    policy: |
      g, system:cluster-admins, role:admin
      g, cluster-admins, role:admin
----

Die hier gesetzten Rechte beziehen sich auf ArgoCD selbst. Wer Mitglied dieser Gruppen ist, hat Admin-Rechte in ArgoCD. Wenn Sie einen normalen User berechtigen wollen, dann erstellen Sie in OpenShift eine Gruppe "cluster-admins" und fügen Sie den OpenShift-User, der Rechte in ArgoCD haben soll, zu der Gruppe hinzu. Sie können die Gruppe natürlich auch anders nennen, müssen dann aber auch in der obigen Gruppenkonfiguration den Gruppennamen anpassen.

Per Default hat ArgoCD auch einen Admin-User, der sich über die Oberfläche anmelden kann. Wie dieser zu nutzen ist, entnehmen Sie bitte der ArgoCD Dokumentation. In dieser Konfiguration wurde dieser aus Sicherheitsgründen deaktiviert:

[source,yaml]
----
spec:
  disableAdmin: true
----

Die weitere Konfiguration der Instanz ist die Standard-Konfiguration und daher unverändert.

=== Allgemeiner Hinweis: Anlegen von Namespaces

Man kann bei der Anlage von Applikationen in ArgoCD definieren, ob ArgoCD auch gleich den Namespace mit anlegen soll. Das ist nett, aber nur bedingt hilfreich. Denn Red Hat GitOps kann dann den Namespace anlegen, aber nichts in dem Namespace ausrollen.

Dies liegt nicht am Serviceaccount, der durch Red Hat GitOps angelegt wird. Der Serviceaccount von ArgoCD benötigt dafür keine weiteren Rechte. Damit ein Projekt von dieser ArgoCD-Instanz gemanaged werden kann, muss der Namespace des Projekts aber ein Label haben, damit die Rechte gewährleistet sind. Der Value des Labels ist der Name des Namespaces, in der die GitOps Instanz liegt, die den Namespace managen soll:

[source,yaml]
----
labels:
  argocd.argoproj.io/managed-by: openshift-gitops
----

Dadurch wird ein neues Rolebinding für den Serviceaccount auf diesen Namespace erstellt und Red Hat GitOps kann Ressourcen in dem Namespace managen.

Daher ist es sinnvoller, die Namespaces nicht durch die Konfiguration der ArgoCD-Applikation anlegen zu lassen, sondern als Ressource mit im Git zu hinterlegen, so dass ArgoCD diese übernimmt. ArgoCD erstellt die Ressource "Namespace" immer vor dem Ausrollen anderer Ressourcen. Die Default Reihenfolge ist: Namespace, Kubernetes Ressourcen, Custom Ressourcen. Das lässt sich aber über Sync Waves auch genauer definieren, wenn man möchte.

(In der neuen Version von ArgoCD gibt es die Möglichkeit, dass man bei der Definition der ArgoCD Applikation nicht nur konfigurieren kann, dass ArgoCD den Namespace erstellt, sondern dort auch direkt Labels und Annotations mit erstellen kann, da dies in vielen Szenarien hilfreich ist, unter anderem auch Istio etc. Dies ist jedoch in der aktuellen Version des Red Hat GitOps Operators noch nicht umgesetzt. https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/ )

== Erstellen eines Applikationsprojekts

Datei: 3_appproject.yaml

Zunächst gibt es in ArgoCD immer das Applikationsprojekt "Default". Alle Applikationen, die nicht einem Applikationsprojekt zugewiesen werden, kommen automatisch in das Applikationsprojekt "Default".

In einem Applikationsprojekt können Berechtigungen und weitere Konfigurationen für die zugehörigen Applikationen konfiguriert werden. Wer darf was in ArgoCD bei den zugewiesenen Applikationen? Welche Repositories können verwendet werden? Usw.

In diesem Beispiel werden nur die Berechtigungen für die User gesetzt. Wer Mitglied der Gruppe "cluster-admins" ist, hat alle Rechte in ArgoCD bei den zu diesem Applikationsprojekt gehörenden Applikationen.

[source,yaml]
----
  roles:
    - description: Alle Rechte
      groups:
        - cluster-admins
      name: admin
      policies:
        - 'p, proj:applications:admin, applications, *, applications/*, allow'
----

== Zugriff für ArgoCD auf CustomRessourceDefinitions, Limitanges und ResourceQuotas gestatten

Datei: 4_additional_role.yaml +
Datei: 5_additional_clusterrolebinding.yaml

Der ArgoCD Instanz fehlen nun noch Berechtigungen, um mit Custom Ressource Definitions, LimitRanges und ResourceQuotas umzugehen. Diese Berechtigung wird über die obigen Dateien hinzugefügt.

[source,yaml]
----
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crd-admin
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["limitranges","resourcequotas"]
  verbs: ["*"] 
----

== Einfaches Secret Management mit GitOps

Wenn man mit OpenShift arbeitet, benötigt man auch Secrets. Diese möchte man aber nicht einfach so in seinem Git ablegen. Es gibt zahlreiche professionelle Tools, um dies zu lösen. Sowohl die Cloudprovider bieten hier Lösungen an (z.B. Azure Vault) als auch andere Anbieter wie das Hashicorp Vault. Jedoch möchte man, wenn man privat ein wenig experimentiert, oft keine derart große und Umfangreiche Lösung haben. Hier bietet sich das Gespann "Mozilla SOPS" und "AGE" an. Red Hat hat eine sehr schöne Anleitung geschrieben, wie man dies in sein GitOps integriert:

https://cloud.redhat.com/blog/a-guide-to-gitops-and-secret-management-with-argocd-operator-and-sops

Dazu installiert man sich einmal "Age" auf dem eigenen PC. ("Age" wird dabei Deutsch, nicht Englisch ausgesprochen.): https://github.com/FiloSottile/age#installation

Nun erstellt man sich einen Public und einen Private Key mit Age und speichert diesen in einer Datei:

[source]
----
age-keygen -o age.agekey
----

Der Public Key wird dabei direkt angezeigt, beide Keys werden in der erstellten Datei gespeichert. Diesen Private Key müssen wir in unserem OpenShift im Namespace von Gitops hinterlegen:

[source]
----
oc create secret generic sops-age --namespace=openshift-gitops --from-file=key.txt=age.agekey
----

Jetzt passen wir die Installation unserer GitOps Instanz an. Dazu als einfachen Weg die YAML der GitOps Instanz über die Weboberfläche des Clusters aufrufen und etwas im Abschnitt "repo" hinzufügen. Dadurch wird das eben erstellte Secret gemounted und über einen Init-Container "ksops" installiert. KSOPS dient dazu, unsere Secrets am Ende wieder zu entschlüsseln. Die Dinge, die bereits im Abschnitt "repo" stehen, bleiben dort auch stehen. Das unten stehende kommt lediglich zusätzlich in diesen Abschnitt:

[source,yaml]
----
  repo:
    env:
    - name: XDG_CONFIG_HOME
      value: /.config
    - name: SOPS_AGE_KEY_FILE
      value: /.config/sops/age/keys.txt
    volumes:
    - name: custom-tools
      emptyDir: {}
    - name: sops-age
      secret:
        secretName: sops-age
    initContainers:
    - name: install-ksops
      image: viaductoss/ksops:v3.0.2
      command: ["/bin/sh", "-c"]
      args:
      - 'echo "Installing KSOPS..."; cp ksops /custom-tools/; cp $GOPATH/bin/kustomize /custom-tools/; echo "Done.";'
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
    volumeMounts:
    - mountPath: /usr/local/bin/kustomize
      name: custom-tools
      subPath: kustomize
    - mountPath: /.config/kustomize/plugin/viaduct.ai/v1/ksops/ksops
      name: custom-tools
      subPath: ksops
    - mountPath: /.config/sops/age/keys.txt
      name: sops-age
      subPath: keys.txt
----

Nun installieren wir uns auf dem eigenen PC noch SOPS: https://github.com/mozilla/sops/releases

Als einfaches Beispiel wollen wir einfach ein Secret verschlüsselt im Git hinterlegen und dann auf den Cluster mit GitOps so ausrollen, dass das Secret entschlüsselt im Cluster liegt.

Ordner: my-secret

Wir erstellen zunächst die Datei, die eine Regel für SOPS hinterlegt:

Dateiname: ".sops.yaml" (direkt im Ordner "my-secret", nicht im Unterordner "my-app")

[source]
----
creation_rules:
  - path_regex: .*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: age1j8r0n4pr8f4uzcd7g84zac45xl8jv8jqhj7uv3f4s0ep43yhh5vsxr7lcc----
----

Die hier angegebene "path_regex" bedeutet, nach beliebigen Dateien (.*) sucht, die dann mit ".sops.yaml" oder ".sops.yml" enden. Beispielsweise eben einer Datei namens "my_secret.sops.yaml"
Ins Feld "age" kommt der Public Key, den uns Age vorhin angezeigt hat und der auch in der von Age erstellten Datei zu finden ist.

Nun benötigen wir irgendein Secret. Hier ein Beispiel:

Dateiname: my_secret.sops.yaml

[source]
----
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  username: admin
  password: totalgeheim
----

Dieses Secret verschlüsseln wir nun mit SOPS auf dem eigenen PC. Dazu führen wir im Ordner "my_secret" diesen Befehl aus:

[source]
----
sops --encrypt --in-place .\my_secret.sops.yaml
----

SOPS sucht dabei automatisch nach der Konfigurationsdatei mit dem Namen ".sops.yaml", so dass wir dem Befehl keine weiteren Parameter mitgeben müssen. Dabei wird die Datei verschlüsselt und unter dem gleichen Namen (--in-place) wieder gespeichert. Unser Secret sieht nun so aus:

[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
    name: mysecret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:FpB+53Q=,iv:fka8v2hqD+/GQL5nr+FC1berFiy8+SWonJaNM3eS1nA=,tag:k2zdZw6iklTzD92bJGucSg==,type:str]
    password: ENC[AES256_GCM,data:bqXmWW95zj4SJxI=,iv:ePPJnSBp6KCvulps61Z21YPn1w+w+ug/RTPYAh4Lac0=,tag:B+Vs5pDSONhnKmQRp7UZ4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j8r0n4pr8f4uzcd7g84zac45xl8jv8jqhj7uv3f4s0ep43yhh5vsxr7lcc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlb2EwY0pKVGU4TzNOc09X
            MktBZjhqbmhKcWJLVzFoRUNyOFJ5cDdITDFNCkJnVWcrVXhialU0V2lVNUlDRWZD
            KzhBVm8vN090R29SMld4cXh2aXphdW8KLS0tIG9wOHNTL0kyQTA4cHV4UHZPNVlJ
            M0FiL2UyWis1eDk4TFNpMVcwQzFtbzQKFjFT7FAAptXZbLCUTdTpZD21b5QODw+Q
            pM9wreHRId8fUsVYle/3yYB0jlzSxpym+O/Sk+cxseveuuXn2fphsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-19T15:05:50Z"
    mac: ENC[AES256_GCM,data:u0oTVY1UbvEFBj/pBShi1/Ys2mVxe2MiGwDZI6TigCskOrDu7zVDZ9BZxRnmmy+bBvpvzPSriwVuiM/9LSgSw3bSmcDsWKCUwPTVukOfNvQm9t3XEe0WG2R4m4S3Wlztl9ttIEzniMkoqhTtuLsuL3GHxRj5akKwAkxn6jAuN/M=,iv:C93R9pkdCsYzT4Gt0vlapaHT/O7t3HDVMat9HGljoK4=,tag:QOCGIC+9Fs1ZDgCMXUm2CA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
----


== Erstellen einer App of Apps

Datei: 7_application_app_of_apps.yaml

Man könnte nun einzelne ArgoCD Applications für jede Applikation manuell installieren. Einfach wird dies, wenn wir eine "App of Apps" nutzen.

Wir hinterlegen dazu alle unsere ArgoCD Application Yaml Dateien in einem Ordner in unserem Git (hier in diesem Repostitory der Ordner "app_of_apps"). Dann schreiben wir eine einzige ArgoCD Application Yaml, die auf diesen Ordner als Quelle verweist (eine kleine Erklärung folgt im Anschluss):

[source,yaml]
----
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  project: applications
  source:
    path: app_of_apps
    repoURL: 'https://github.com/saschasgit/rh-gitops.git'
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
----

Wenn wir dann ArgoCD starten, ist zunächst nur eine Applikation vorhanden, diese "app-of-apps". Sobald wir diese synchronisieren, werden die Applikationen, für die wir im "app_of_apps" Ordner ArgoCD Application Yamls hinterlegt haben, als Applikationen im ArgoCD erscheinen.


== Beispielapplikation

Um nun eine Beispielapplikation zu erstellen, legt man eine ArgoCD-Applikation an. Diese hat im Wesentlichen drei relevante Informationen:

Destination: Der Name des OpenShift-Projekts, wo die Applikation installiert werden soll. Dazu die Angabe des Servers, damit ArgoCD zugreifen kann. Wenn ArgoCD im gleichen OpenShift-Cluster liegt, reicht für den Server die Angabe: 'https://kubernetes.default.svc'

Source: Angabe des Repositories, wo die Manifeste der Applikationen liegen.

SyncPolicy: Die Konfiguration, wie ArgoCD syncen soll.

Wenn diese Datei ausgerollt wird, entsteht noch keine Applikation in OpenShift, da ArgoCD hier nicht automatisch synchronisiert (man könnte das automatisieren, indem man diei entsprechende Option unter SyncPolicy setzt). Aber in ArgoCD sieht man nun diese Applikation. In ArgoCD kann man nun bei der Applikation auf "Sync" klicken und die Applikation nach OpenShift ausrollen.

Und damit haben wir nun eine über ArgoCD ausgerollte Applikation.

== Beispiel für einen Patch

Datei: 8a_application_bookinfo_ssa.yaml +
Datei: 8b_application_group_ssa.yaml

Ich habe aber noch zwei Dateien hinzugefügt, um etwas zu demonstrieren.

Der Red Hat Gitops Operator kann ab der Version 1.7 nicht nur Applikationen ausrollen, sondern endlich auch bestehende Ressourcen patchen. Dies geht über Server-Side-Apply.

Wichtig ist hier, dass diese beiden Angaben in der SyncPolicy stehen:

[source,yaml]
----
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - Validate=false
----

Die erste konfiguriert, dass hier ein Server-Side-Apply gemacht wird.
Die zweite ist wichtig, da bei einem Patch nur ein Teil der YAML angegeben wird, eine "Partial YAML". Dies würde sonst in einem Validierungsfehler enden.

Das erste Beispiel erstellt eine Applikation, welches folgende Datei auf den Cluster synchronisiert und damit die Replicas der Produktpage erhöht:

[source,yaml]
----
kind: Deployment
apiVersion: apps/v1
metadata:
  name: productpage-v1
  labels:
    info: ssa-test
spec:
  replicas: 3
----

Wie man sieht, wird nur der Teil ded Deployments beschrieben, welches die Anzahl der Replicas enthält.

Das zweite Beispiel kümmert sich um eine Ressource, die nicht in einem Namespace liegt, eine Gruppe. Es wird ein Label hinzugefügt.

[source,yaml]
----
kind: Group
apiVersion: user.openshift.io/v1
metadata:
  name: cluster-admins
  labels:
    info: ssa-test
----

Nun wird in einer ArgoCD-Applikation immer ein Namespace als "Destination" angegeben, jedoch haben wir hier eine Ressource, die nicht zu einem Namespace gehört. In diesem Fall muss ein Namespace angegeben werden, der auf dem Cluster existiert, weswegen sich natürlich "Default" anbietet. Die Ressource wird dann natürlich korrekt ohne Zugehörigkeit zu einem Namespace angelegt:

[source,yaml]
----
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: group-ssa
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
----

# oc get $(oc api-resources --verbs=list -o name | awk '{printf "%s%s",sep,$0;sep=","}')  --ignore-not-found --all-namespaces -o=custom-columns=KIND:.kind,NAME:.metadata.name,NAMESPACE:.metadata.namespace --sort-by='metadata.namespace'