kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    argocd.argoproj.io/syncwave: {{ $.Values.syncwaves.role | quote }}
  name: job-wait-neuvector-operator-role
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - jaegertracing.io
    resources:
      - jaegers


