apiVersion : kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-resources-to-buildconfig
  annotations:
    policies.kyverno.io/title: Add Resources to BuildConfig
    policies.kyverno.io/category: Other
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: BuildConfig
    policies.kyverno.io/description: >-
      If a BuildConfig does not specify at least resource requests it can happen
      that the build will be slow because the default-values of the quotas settings
      will be applied.
      This policy checks if settings for memory and cpu requests are available and if not
      applies the settings below.
      This policy will exclude all namespaces that start with "openshift" or "kube".
      IMPORTANT: The setting "schemaValidation: false" is because of a bug in the actual
      kyverno version and can be deleted in 1.9+.
      IMPORTANT: If there is no nodeselector or the nodeselector is set to "null", than
      this version of kyverno shows in the annotation of the buildconfig "removed /spec/nodeSelector".
      This seems to be a bug in this version. The nodeselector will not be touched, only the resources.
spec:
  background: false
  schemaValidation: false
  rules:
  - name: add-resources-to-buildconfig
    match:
      any:
      - resources:
          kinds:
          - BuildConfig
    exclude:
      any:
      - resources:
          namespaces:
          - openshift*
          - kube*
    preconditions:
      any:
      - key: "{{request.operation || 'BACKGROUND'}}"
        operator: AnyIn
        value:
        - CREATE
        - UPDATE
    mutate:
      patchStrategicMerge:
        spec:
          resources:
            requests:
              +(memory): "1Gi"
              +(cpu): "1"
