apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: {{ $.Values.syncwaves.patch | quote }}
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  name: patch-neuvector-operators
  namespace: {{ $.Values.namespace | quote }}
spec:
  selector: {}
  template:
    metadata:
      name: patch-neuvector-operators
    spec:
      containers:
        - name: patch-neuvector-operators
          image: registry.redhat.io/openshift4/ose-cli
          command:
            - /bin/bash
            - -c
            - |
              export HOME=/tmp/clo
              echo ""
              # echo -n "Wait 20s and patching the approval for the operators of DevWorkSpace."
              # sleep $SLEEP
              # oc get installplan -n openshift-operators -l operators.coreos.com/devworkspace-operator.openshift-operators= -oname | xargs -r -n 1 oc -n openshift-operators patch --type json --patch '[{"op": "replace", "path": "/spec/approved", "value": true}]'
              # echo ""
              echo -n "Wait 20s and patching the approval for the operators of WebTerminal."
              sleep $SLEEP
              oc get installplan -n openshift-operators -l operators.coreos.com/web-terminal.openshift-operators= -oname | xargs -r -n 1 oc -n openshift-operators patch --type json --patch '[{"op": "replace", "path": "/spec/approved", "value": true}]'
              echo -n "DONE"
          env:
          - name: SLEEP
            value: "20"
      restartPolicy: OnFailure
      serviceAccount: job-patch-operator-sa
      serviceAccountName: job-patch-operator-sa
      terminationGracePeriodSeconds: 30            
