apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-configurator
  namespace: namespace-configuration-operator
spec:
  destination:
    namespace: namespace-configuration-operator
    server: 'https://kubernetes.default.svc'
  project: applications
  source:
    path: subscription
    repoURL: 'https://github.com/saschasgit/rh-gitops_and_namespaces.git'
    targetRevision: HEAD
  syncPolicy:
    syncOptions: