apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-secret-namespace
  namespace: openshift-gitops
spec:
  destination:
    namespace: my-secret
    server: 'https://kubernetes.default.svc'
  project: applications
  source:
    path: applications/my_secret_namespace
    repoURL: 'https://github.com/saschasgit/rh-gitops.git'
    targetRevision: HEAD
  syncPolicy:
    syncOptions:

