apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: openshift-gitops
spec:
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  project: applications
  source:
    chart: kyverno
    repoURL: https://kyverno.github.io/kyverno
    targetRevision: 2.6.0
    helm:
      parameters:
        - name: securityContext
          value: null
        - name: replicaCount
          value: "3"
  syncPolicy:
    syncOptions:
      - Replace=true