apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-selected-policies
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: applications
  source:
    path: kyverno-policies
    repoURL: 'https://github.com/saschasgit/kyverno.git'
    targetRevision: HEAD
  syncPolicy:
    syncOptions: