apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: openshift-gitops
spec:
  destination:
    namespace: kyverno
    server: 'https://kubernetes.default.svc'
  project: applications
  source:
    path: applications/kyverno
    repoURL: 'https://github.com/saschasgit/rh-gitops.git'
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - Replace=true

kind: Namespace
apiVersion: v1
metadata:
  name: kyverno
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops